// SPDX-License-Identifier: Apache-2.0
export {
  SLUG_RULE,
  ROS_NAME_RULE,
  ROS_TYPE_NAME_RULE,
  FIELD_PATH_RULE,
  slug,
  rosName,
  rosTypeName,
  fieldPath,
  wireSeqCursor,
  wireTimestampMs,
  applyErrorKind,
  applyError,
} from './common.js'
export type { ApplyErrorKind, ApplyError } from './common.js'
export {
  MCP_PROTOCOL_VERSION,
  MCP_ENDPOINT_PATH,
  mcpAppEndpointPath,
  MCP_APP_PATHS,
  MCP_TOOL_NAME_MAX,
  MCP_ASSET_LINK_PATH,
  MCP_ASSET_LINK_TTL_MS,
  mcpToolNamePattern,
  mcpToolKind,
  mcpExposure,
  mcpCapabilities,
  mcpRobotDatasheet,
  mcpRolePreviewResponse,
} from './mcp.js'
export type {
  McpAppPaths,
  McpToolKind,
  McpExposure,
  McpCapabilities,
  McpRobotDatasheet,
  McpRolePreviewResponse,
} from './mcp.js'
export {
  PROTOCOL_VERSION,
  PROTOCOL_VERSIONS,
  PROTOCOL_SUNSET_DAYS,
  LATEST_BRIDGE_VERSION,
  protocolStatus,
  minimumProtocolVersion,
  sunsetOf,
  statusFromTable,
  bridgeHello,
  cloudHelloOk,
  cloudHelloError,
  cloudPing,
  bridgePong,
  bridgeLinkMode,
  datapointFrame,
  bridgeState,
  cloudConfig,
  bridgeConfigApplied,
  cloudIntrospectRequest,
  bridgeIntrospect,
  cloudTypeRequest,
  bridgeTypeDefinitions,
  cloudInvoke,
  cloudCancel,
  cloudPublish,
  bridgeJobUpdate,
  bridgeJobLost,
  snapshotHeader,
  cloudCameraStart,
  cloudCameraStop,
  bridgeCameraState,
  SNAPSHOT_MAX_BYTES,
  CLOSE_ROBOT_DELETED,
  CLOSE_TOKEN_ROTATED,
  // Assets.
  bridgeAssetsAvailable,
  cloudAssetRequest,
  bridgeAssetProgress,
  // Addressing.
  activeJob,
  DEFAULT_PATIENCE_MS,
  MAX_PATIENCE_MS,
  MIN_PATIENCE_MS,
} from './protocol.js'
export type {
  ProtocolVersionEntry,
  ProtocolStatus,
  BridgeHello,
  CloudHelloOk,
  CloudHelloError,
  CloudPing,
  BridgePong,
  BridgeLinkMode,
  DatapointFrame,
  BridgeState,
  CloudConfig,
  BridgeConfigApplied,
  CloudIntrospectRequest,
  BridgeIntrospect,
  CloudTypeRequest,
  BridgeTypeDefinitions,
  CloudInvoke,
  CloudCancel,
  CloudPublish,
  BridgeJobUpdate,
  BridgeJobLost,
  SnapshotHeader,
  CloudCameraStart,
  CloudCameraStop,
  BridgeCameraState,
  ActiveJob,
  BridgeAssetsAvailable,
  CloudAssetRequest,
  BridgeAssetProgress,
} from './protocol.js'
export { jobState, job, jobEvent, busyDetails, publisherBusyDetails, jobQueueFullDetails } from './jobs.js'
export type {
  JobState,
  Job,
  JobEvent,
  BusyDetails,
  PublisherBusyDetails,
  JobQueueFullDetails,
} from './jobs.js'
export {
  JOB_RUN_PAGE_MAX,
  JOB_RUN_RETENTION_DAYS,
  jobActor,
  jobRunKind,
  jobRun,
  jobRunQuery,
  jobRunListResponse,
  jobRunSummaryQuery,
  jobRunSummary,
} from './jobs.js'
export type { JobActor, JobRunKind, JobRun, JobRunQuery, JobRunListResponse, JobRunSummary } from './jobs.js'
export {
  FLEETLESS_FORMAT_VERSION,
  RESERVED_SLUGS,
  parameterType,
  parameterSpec,
  parameterMap,
  serviceDescription,
  parameterDescription,
  messageTemplate,
  messageRef,
  messageBody,
  messageMap,
  PLACEHOLDER_RE,
  placeholderNames,
  actionConfig,
  serviceConfig,
  publisherConfig,
  cameraConfig,
  alertCondition,
  datapointAlert,
  rateThrottleHz,
  datapointNumeric,
  datapointRetention,
  datapointChart,
  datapointConfig,
  lowBandwidthSection,
  LOW_BANDWIDTH_DEFAULTS,
  robotConfigDoc,
  validationIssue,
  configState,
  snapshotIntervalSeconds,
  // The defaults the format names, so nobody invents them twice.
  ALERT_SEVERITY_DEFAULT,
  ALERT_ENABLED_DEFAULT,
  RETENTION_INTERVAL_SECONDS_DEFAULT,
  CHART_WINDOW_MINUTES_DEFAULT,
  // Retention, history and quotas.
  cameraSource,
  cameraCredentials,
} from './config.js'
export type { CameraSource } from './config.js'
export type {
  ParameterType,
  ParameterSpec,
  ActionConfig,
  ServiceConfig,
  PublisherConfig,
  CameraConfig,
  CameraCredentials,
  AlertCondition,
  DatapointAlert,
  DatapointNumeric,
  DatapointRetention,
  DatapointChart,
  DatapointConfig,
  LowBandwidthSection,
  RobotConfigDoc,
  ValidationIssue,
  ConfigState,
} from './config.js'
/**
 * The one account of what is wrong with a configuration document, shared by
 * every layer that reports on one. See `config-issues.ts`'s header for why a
 * second copy of this vocabulary is a defect, not a convenience.
 */
export {
  DOCUMENT_ROOT_PATH,
  EXPOSURE_SECTIONS,
  schemaIssues,
  formatPath,
  splitFormatPath,
  configSchemaHash,
} from './config-issues.js'
export type { SchemaIssue, ExposureSection } from './config-issues.js'
export { rosGraphEntry, rosGraph, typeField, typeDefinition, parameterFieldsOf } from './introspection.js'
export type { RosGraphEntry, RosGraph, TypeField, TypeDefinition } from './introspection.js'
export {
  robot,
  patchRobotResponse,
  robotToken,
  createRobotRequest,
  createRobotResponse,
  robotTokenRotateResponse,
  jointStatePutRequest,
  jointStatePutResponse,
  exposureCounts,
  protocolStatusValue,
  robotListItem,
  robotListResponse,
  datapointValue,
  robotDetailResponse,
  configDraftResponse,
  putConfigDraftRequest,
  publishConfigResponse,
  configVersionsResponse,
  configVersionResponse,
  introspectionResponse,
  typesResponse,
  fetchTypesRequest,
  fetchTypesResponse,
  datapointDescriptor,
  datapointListResponse,
  robotDetailsDoc,
  putRobotDetailsResponse,
  putRobotDetailsRequest,
  invokeRequest,
  invokeResponse,
  // Addressing.
  cancelRequest,
  releaseLiveQuery,
  serviceCallResponse,
  invokeOrServiceResponse,
  publishRequest,
  jobResponse,
  robotJobsResponse,
  rateLimitDetails,
  exposure,
  exposureListResponse,
  SNAPSHOT_HEADERS,
  ASSET_UPLOAD_HEADERS,
  cameraDescriptor,
  cameraListResponse,
  liveSessionResponse,
  snapshotMetaResponse,
  // Retention, history, quotas.
  historyQuery,
  historySamplesResponse,
  historyBucketsResponse,
  historyResponse,
  orgQuotas,
  orgQuotaUsage,
  orgQuotaUsageCounts,
  robotDeletionSummary,
  RESOURCE_HEALTH_STATES,
  resourceHealthState,
  resourceHealthListResponse,
  orgHealthQuery,
  robotDeleteQuery,
  // Robot rename, slug rename.
  patchRobotRequest,
  renameSlugRequest,
  renameSlugResponse,
  slugUsageResponse,
} from './rest.js'
export type {
  HistoryQuery,
  HistorySamplesResponse,
  HistoryResponse,
  HistoryBucketsResponse,
  OrgQuotas,
  OrgQuotaUsage,
  OrgQuotaUsageCounts,
  RobotDeletionSummary,
  ResourceHealthState,
  ResourceHealthListResponse,
  OrgHealthQuery,
  RobotDeleteQuery,
  PatchRobotRequest,
  RenameSlugRequest,
  RenameSlugResponse,
  SlugUsageResponse,
} from './rest.js'
export {
  LATENCY_BUCKET_MS,
  BRIDGE_LATENCY_RETENTION_DAYS,
  MAX_LATENCY_BUCKETS_PER_RESPONSE,
  latencyBucket,
  robotLatencySeries,
  orgLatencyQuery,
  orgLatencyResponse,
  USAGE_WINDOW_MAX_DAYS,
  usageMetric,
  usageDay,
  orgUsageQuery,
  usageRow,
  orgUsageResponse,
} from './rest.js'
export type { LatencyBucket, RobotLatencySeries, OrgLatencyResponse } from './rest.js'
export type { UsageMetric, OrgUsageQuery, UsageRow, OrgUsageResponse } from './rest.js'
export type {
  Robot,
  PatchRobotResponse,
  CreateRobotRequest,
  CreateRobotResponse,
  RobotTokenRotateResponse,
  JointStatePutRequest,
  JointStatePutResponse,
  ExposureCounts,
  ProtocolStatusValue,
  RobotListItem,
  RobotListResponse,
  DatapointValue,
  RobotDetailResponse,
  ConfigDraftResponse,
  PutConfigDraftRequest,
  PublishConfigResponse,
  ConfigVersionsResponse,
  ConfigVersionResponse,
  IntrospectionResponse,
  TypesResponse,
  FetchTypesRequest,
  FetchTypesResponse,
  DatapointDescriptor,
  DatapointListResponse,
  RobotDetailsDoc,
  PutRobotDetailsResponse,
  PutRobotDetailsRequest,
  InvokeRequest,
  InvokeResponse,
  CancelRequest,
  ReleaseLiveQuery,
  ServiceCallResponse,
  InvokeOrServiceResponse,
  PublishRequest,
  JobResponse,
  RobotJobsResponse,
  RateLimitDetails,
  Exposure,
  ExposureListResponse,
  CameraDescriptor,
  CameraListResponse,
  LiveSessionResponse,
  SnapshotMetaResponse,
} from './rest.js'
export {
  clientAuth,
  authOk,
  authError,
  clientInvoke,
  clientCancel,
  clientPublish,
  commandResult,
  errorFrame,
  clientSubscribe,
  clientUnsubscribe,
  subscribeError,
  datapointEvent,
  resourceHealthEvent,
  resourceHealthCleared,
  liveSessionEndReason,
  liveSessionEvent,
  ORG_EVENT_SAMPLE_INTERVAL_MS,
  ORG_EVENT_ORG_CEILING_PER_SECOND,
  ORG_EVENT_BUFFER_SIZE,
  ORG_EVENT_BUFFER_IDLE_MS,
  ORG_EVENT_DETAIL_MAX_BYTES,
  orgEventKind,
  orgEventSeverity,
  orgEvent,
  orgEventSubscribe,
  orgEventUnsubscribe,
  orgEventReplay,
  orgEventDropped,
} from './realtime.js'
export type {
  ClientAuth,
  AuthOk,
  AuthError,
  ClientInvoke,
  ClientCancel,
  ClientPublish,
  CommandResult,
  ErrorFrame,
  ClientSubscribe,
  ClientUnsubscribe,
  SubscribeError,
  DatapointEvent,
  ResourceHealthEvent,
  ResourceHealthCleared,
  LiveSessionEndReason,
  LiveSessionEvent,
  OrgEventKind,
  OrgEventSeverity,
  OrgEvent,
  OrgEventSubscribe,
  OrgEventUnsubscribe,
  OrgEventReplay,
  OrgEventDropped,
} from './realtime.js'
export {
  password,
  org,
  patchOrgResponse,
  sessionTokens,
  refreshRequest,
  signUpRequest,
  signUpResponse,
  // 2026-09-04 — the public site (closed beta).
  waitlistRequest,
  developerLoginRequest,
  // The two identity spaces.
  USER_DISPLAY_NAME_MAX,
  orgAdminTier,
  fleetlessUser,
  fleetlessUserListResponse,
  createTeamInviteRequest,
  teamInvite,
  pendingTeamInvite,
  pendingTeamInviteListResponse,
  acceptTeamInviteRequest,
  patchFleetlessUserRequest,
  tierChangeRequest,
  // Identity.
  mailStatus,
  tierRequiredDetails,
  passwordChangeRequest,
  passwordResetRequest,
  passwordResetConfirm,
  idpIssuer,
  // auth/me, org and member patches.
  authMeResponse,
  patchOrgRequest,
  patchAuthMeRequest,
} from './identity.js'
export type {
  Org,
  PatchOrgResponse,
  SessionTokens,
  RefreshRequest,
  SignUpRequest,
  SignUpResponse,
  WaitlistRequest,
  DeveloperLoginRequest,
  OrgAdminTier,
  FleetlessUser,
  FleetlessUserListResponse,
  CreateTeamInviteRequest,
  TeamInvite,
  PendingTeamInvite,
  PendingTeamInviteListResponse,
  AcceptTeamInviteRequest,
  PatchFleetlessUserRequest,
  TierChangeRequest,
  MailStatus,
  TierRequiredDetails,
  PasswordChangeRequest,
  PasswordResetRequest,
  PasswordResetConfirm,
  IdpIssuer,
  AuthMeResponse,
  PatchOrgRequest,
  PatchAuthMeRequest,
} from './identity.js'
export {
  appIdentifier,
  app,
  appListResponse,
  createAppRequest,
  updateAppRequest,
  serverKeyToken,
  serverKey,
  serverKeyListResponse,
  createServerKeyResponse,
  role,
  roleListResponse,
  rolePermissions,
} from './apps.js'
export type {
  App,
  AppListResponse,
  CreateAppRequest,
  UpdateAppRequest,
  ServerKey,
  ServerKeyListResponse,
  CreateServerKeyResponse,
  Role,
  RoleListResponse,
  RolePermissions,
} from './apps.js'
export {
  clientLoginRequest,
  clientRefreshRequest,
  clientLogoutRequest,
  clientRegisterRequest,
  clientVerifyEmailRequest,
  clientResendVerificationRequest,
  clientPasswordResetRequest,
  clientPasswordResetConfirmRequest,
  clientAcceptInvitationRequest,
  CLIENT_OIDC_CALLBACK_PATH,
  clientProviderListQuery,
  clientProviderListResponse,
  clientOidcStartQuery,
  clientOidcCallbackQuery,
  clientOidcExchangeRequest,
  clientOidcErrorCode,
  clientMcpInteraction,
  clientMcpInteractionDecisionResponse,
  mcpConsentGrant,
  mcpConsentGrantListResponse,
  clientIdentity,
} from './client-auth.js'
export type {
  ClientLoginRequest,
  ClientRefreshRequest,
  ClientLogoutRequest,
  ClientRegisterRequest,
  ClientVerifyEmailRequest,
  ClientResendVerificationRequest,
  ClientPasswordResetRequest,
  ClientPasswordResetConfirmRequest,
  ClientAcceptInvitationRequest,
  ClientProviderListQuery,
  ClientProviderListResponse,
  ClientOidcStartQuery,
  ClientOidcCallbackQuery,
  ClientOidcExchangeRequest,
  ClientOidcErrorCode,
  ClientMcpInteraction,
  ClientMcpInteractionDecisionResponse,
  McpConsentGrant,
  McpConsentGrantListResponse,
  ClientIdentity,
} from './client-auth.js'
export { clientRobotListItem, clientRobotListResponse } from './client-robots.js'
export type { ClientRobotListItem, ClientRobotListResponse } from './client-robots.js'
// The per-app identity space.
export {
  APP_USER_DISPLAY_NAME_MAX,
  APP_URL_PLACEHOLDERS,
  MAIL_TEMPLATE_VARIABLES,
  DEFAULT_MAIL_TEMPLATES,
  providerSlug,
  appUserStatus,
  appUser,
  appUserListResponse,
  createAppUserRequest,
  patchAppUserRequest,
  createAppInvitationRequest,
  appInvitation,
  pendingAppInvitation,
  appInvitationListResponse,
  appOidcProvider,
  appOidcProviderListResponse,
  createAppOidcProviderRequest,
  patchAppOidcProviderRequest,
  appUrlTemplate,
  allowedOrigin,
  emailDomain,
  appAuthConfig,
  putAppAuthRegistrationRequest,
  putAppAuthUrlsRequest,
  putAppAuthMcpRequest,
  mailTemplateKind,
  appMailTemplate,
  appMailTemplateListResponse,
  putAppMailTemplateRequest,
  mailTemplatePreviewRequest,
  mailTemplatePreviewResponse,
  mailTemplateProblemDetails,
  mailOutcome,
} from './app-users.js'
export type {
  AppUserStatus,
  AppUser,
  AppUserListResponse,
  CreateAppUserRequest,
  PatchAppUserRequest,
  CreateAppInvitationRequest,
  AppInvitation,
  PendingAppInvitation,
  AppInvitationListResponse,
  AppOidcProvider,
  AppOidcProviderListResponse,
  CreateAppOidcProviderRequest,
  PatchAppOidcProviderRequest,
  AppAuthConfig,
  PutAppAuthRegistrationRequest,
  PutAppAuthUrlsRequest,
  PutAppAuthMcpRequest,
  MailTemplateKind,
  AppMailTemplate,
  AppMailTemplateListResponse,
  PutAppMailTemplateRequest,
  MailTemplatePreviewRequest,
  MailTemplatePreviewResponse,
  MailTemplateProblemDetails,
  MailOutcome,
} from './app-users.js'
export {
  assetKind,
  URDF_ASSET_NAME,
  asset,
  urdfCompleteness,
  assetListResponse,
  assetsClearResponse,
  missingAssetQuery,
  assetSyncRequest,
  assetSyncResponse,
  assetSyncState,
  assetSyncStatus,
  assetFailure,
  assetFailureKind,
  assetStoreRefusedDetails,
  assetSyncBusyDetails,
  ROBOT_ASSET_STORE_BYTES,
} from './assets.js'
export type {
  AssetKind,
  Asset,
  UrdfCompleteness,
  AssetListResponse,
  AssetsClearResponse,
  MissingAssetQuery,
  AssetSyncRequest,
  AssetSyncResponse,
  AssetSyncState,
  AssetSyncStatus,
  AssetFailure,
  AssetFailureKind,
  AssetStoreRefusedDetails,
  AssetSyncBusyDetails,
} from './assets.js'
export { auditActor, auditEvent, auditQuery, auditListResponse, AUDIT_CSV_COLUMNS, AUDIT_RETENTION_DAYS } from './audit.js'
export type { AuditActor, AuditEvent, AuditQuery, AuditListResponse } from './audit.js'
export {
  alertRowCondition,
  alertSeverity,
  alertState,
  datapointAlertRow,
  alertListResponse,
  orgFiringAlertsResponse,
  orgAlertsQuery,
  datapointDisplay,
  putDatapointDisplayRequest,
} from './alerts.js'
export type {
  AlertRowCondition,
  AlertSeverity,
  AlertState,
  DatapointAlertRow,
  AlertListResponse,
  OrgFiringAlertsResponse,
  OrgAlertsQuery,
  DatapointDisplay,
  PutDatapointDisplayRequest,
} from './alerts.js'
export { apiError, parameterViolation, parameterInvalidDetails, ERROR_CODES } from './errors.js'
export type { ApiError, ParameterViolation, ParameterInvalidDetails, ErrorCode } from './errors.js'
export {
  oauthErrorCode,
  oauthError,
  oauthRedirectResponse,
  oauthCodeTokenRequest,
  oauthRefreshTokenRequest,
  oauthTokenRequest,
  oauthTokenResponse,
  redirectUri,
  codeChallengeMethod,
  oauthAuthorizeQuery,
  dynamicClientRegistrationRequest,
  MCP_DCR_MAX_REDIRECT_URIS,
  dynamicClientRegistrationResponse,
  authorizationServerMetadata,
  protectedResourceMetadata,
} from './oauth.js'
export type {
  OauthErrorCode,
  OauthError,
  OauthRedirectResponse,
  OauthCodeTokenRequest,
  OauthRefreshTokenRequest,
  OauthTokenRequest,
  OauthTokenResponse,
  RedirectUri,
  OauthAuthorizeQuery,
  DynamicClientRegistrationRequest,
  DynamicClientRegistrationResponse,
  AuthorizationServerMetadata,
  ProtectedResourceMetadata,
} from './oauth.js'
export { ROUTES, ROUTE_SECTIONS, IN_HANDLER_ROUTES } from './routes.js'
export type {
  RouteEntry,
  RouteParam,
  RouteAudience,
  RouteAuth,
  RouteSection,
  RouteMethod,
  RouteTransport,
} from './routes.js'
